DROP DATABASE IF EXISTS devbook;
CREATE DATABASE devbook;
USE devbook;

CREATE TABLE usuarios(
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(50) NOT NULL,
  nick VARCHAR(50) NOT NULL UNIQUE,
  email VARCHAR(50) NOT NULL UNIQUE,
  senha VARCHAR(100) NOT NULL,
  criadoEm TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
) ENGINE=INNODB;

CREATE TABLE seguidores(
  usuario_id INT NOT NULL,
  FOREIGN KEY (usuario_id)
  REFERENCES usuarios(id)
  ON DELETE CASCADE,
  seguidor_id INT NOT NULL,
  FOREIGN KEY (seguidor_id)
  REFERENCES usuarios(id)
  ON DELETE CASCADE,
  PRIMARY KEY(usuario_id, seguidor_id)
) ENGINE=INNODB;

CREATE TABLE publicacoes(
  id INT AUTO_INCREMENT PRIMARY KEY,
  titulo VARCHAR(50) NOT NULL,
  conteudo VARCHAR(300) NOT NULL,
  autor_id INT NOT NULL,
  FOREIGN KEY (autor_id)
  REFERENCES usuarios(id)
  ON DELETE CASCADE,
  curtidas INT DEFAULT 0,
  criadaEm TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
) ENGINE=INNODB;